spring:
  h2:    console:      enabled: true  application:    name: CustomerService  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:customerdb    username: sa
    password: saserver:  port: 8080 