spring:
  h2:
    console:
      enabled: true
  application:
    name: ItemService
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:itemdb
    username: sa
    password: sa
server:
  port: 8082